[package]
name = "schnorrkel"
version = "0.8.5"
authors = ["Jeff Burdges <jeff@web3.foundation>"]
readme = "README.md"
license = "BSD-3-Clause"
repository = "https://github.com/w3f/schnorrkel"
documentation = "https://docs.rs/schnorrkel"
keywords = ["cryptography", "ed25519", "curve25519", "signature", "ECC"]
categories = ["cryptography", "no-std"]
description = "Schnorr VRF, signatures, etc. using the Ristretto group"
exclude = [ ".gitignore", "TESTVECTORS", "res/*" ]
edition = "2018"

# [badges]
# travis-ci = { repository = "dalek-cryptography/ed25519-dalek", branch = "master"}

[dependencies.curve25519-dalek]
# git = "https://github.com/dalek-cryptography/curve25519-dalek"
version = "1.2.3"
default-features = false

[dependencies.ed25519-dalek]
version = "1.0.0-pre.2"
default-features = false
optional = true

[dependencies.subtle]
version = "2.2.1"
default-features = false

[dependencies.merlin] 
version = "1.2.1"
# features = ["debug-transcript"]
default-features = false

[dependencies.rand]
version = "0.6.5"
default-features = false
optional = true

[dependencies.rand_core]
version = "0.4.2"
default-features = false

[dependencies.rand_os]
version = "0.1.3"
default-features = false
optional = true

[dependencies.rand_chacha]
version = "0.1.1"
default-features = false
optional = true

[dependencies.serde]
version = "1.0.101"
default-features = false
optional = true

[dependencies.sha2]
version = "0.8.0"
default-features = false

[dependencies.failure]
version = "0.1.5"
default-features = false

[dependencies.zeroize]
version = "0.10.1"
default-features = false
# features = ["zeroize_derive"]

[dev-dependencies]
rand = "0.6.5"
rand_chacha = "0.1.1"
# hex = "0.3.2"
hex-literal = "0.2.1"
sha2 = "0.8.0"
sha3 = "0.8.2"
bincode = "1.2.0"
criterion = "0.3.0"

[[bench]]
name = "schnorr_benchmarks"
harness = false

[features]
default = ["std", "u64_backend", "rand"] # "chacha"
preaudit_deprecated = []
nightly = ["curve25519-dalek/nightly", "rand/nightly"] # "zeroize/nightly"
alloc = ["curve25519-dalek/alloc", "rand_core/alloc"]
chacha = ["rand_chacha"]
std = ["rand_os", "curve25519-dalek/std", "rand/std"] # "failure/std"
stdweb = ["rand_os/stdweb"]
wasm-bindgen = ["rand_os/wasm-bindgen"]
asm = ["sha2/asm"]
yolocrypto = ["curve25519-dalek/yolocrypto"]
u64_backend = ["curve25519-dalek/u64_backend"]
u32_backend = ["curve25519-dalek/u32_backend"]
avx2_backend = ["curve25519-dalek/avx2_backend"]
